training:
  lr: 1e-5
  weight_decay: 1e-7
  batch_size: 4
  iters_per_epoch: 100
  epochs: 100
  checkpointing: True

data:
  image_folder: "/Users/riccardoalberghi/Desktop/GraXpertAI/dataset/train/sharpen_images"
  bkg_folder: "/Users/riccardoalberghi/Desktop/GraXpertAI/dataset/train/psf_catalog"
  num_workers: 0
  images_to_plot: 8

model:
  arch: "unet"
  layer_sizes: [64, 128, 256, 512, 512, 512, 512, 512]
  image_channels: 3

loss:
  loss: "l1"